package com.novapay.wallet_service.dto.request;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.novapay.wallet_service.entity.enums.CurrencyCode;
import com.novapay.wallet_service.entity.enums.WalletStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.Setter;


@JsonInclude(JsonInclude.Include.NON_NULL)
@Getter
@Setter
public class WalletRequest {

    @Schema(example = "1", description = "Wallet ID (Usually generated by system, optional in create request)")
    @Positive(message = "Wallet id must be positive")
    private Long id;
    @Schema(example = "WALLET-89XJ21", description = "Unique wallet number")
    @Size(min = 6, max = 30, message = "Wallet number must be between 6 and 30 characters")
    @Pattern(regexp = "^[A-Z0-9-]+$", message = "Wallet number must contain only uppercase letters, numbers and dash")
    private String walletNumber;
    @Schema(example = "101", description = "User ID who owns the wallet")
    @NotNull(message = "UserId is required")
    @Positive(message = "UserId must be positive")
    private Long userId;
    @Schema(example = "ACTIVE",description = "Wallet status")
    @NotNull(message = "Wallet status is required")
    private WalletStatus status;
    @Schema(example = "INR",description = "Wallet currency")
    @NotNull(message = "Currency is required")
    private CurrencyCode currency;
}
