spring:
  application:
    name: wallet-service
  config:
    import: "configserver:http://localhost:8089/"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "Wallet Service"
    description: "Wallet Management Service"
    version: "1.0"

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost